# Harfbuzz settings
add_definitions(
   -DHAVE_ATEXIT
   -DHB_EXTERN=
   -DHB_NO_UNICODE_FUNCS
   -DHB_NDEBUG
   -DFT2_BUILD_LIBRARY
)

list(APPEND GUI_PUBLIC_INCLUDES
   QAbstractTextDocumentLayout
   QAbstractGraphicsShapeItem
   QAbstractUndoItem
   QFont
   QFontDatabase
   QFontInfo
   QFontMetrics
   QFontMetricsF
   QGlyphRun
   QRawFont
   QStaticText
   QSupportedWritingSystems
   QSyntaxHighlighter
   QTextCursor
   QTextBlock
   QTextBlockFormat
   QTextBlockGroup
   QTextBlockUserData
   QTextCharFormat
   QTextDocument
   QTextDocumentFragment
   QTextDocumentWriter
   QTextFormat
   QTextFragment
   QTextFrame
   QTextFrameFormat
   QTextFrameLayoutData
   QTextInlineObject
   QTextImageFormat
   QTextLayout
   QTextLine
   QTextListFormat
   QTextLength
   QTextList
   QTextObject
   QTextObjectInterface
   QTextOption
   QTextTable
   QTextTableCell
   QTextTableCellFormat
   QTextTableFormat
)

list(APPEND GUI_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qabstractgraphicsshapeitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qabstracttextdocumentlayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qabstractundoitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfont.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontdatabase.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontinfo.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontmetrics.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontmetricsf.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qglyphrun.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qrawfont.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qstatictext.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qsupportedwritingsystems.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qsyntaxhighlighter.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextblock.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextblockformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextblockgroup.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextblockuserdata.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcharformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcursor.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocument.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentfragment.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentwriter.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextfragment.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextframe.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextframeformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextframelayoutdata.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextinlineobject.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextimageformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextline.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlistformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlength.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlist.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextobject.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextobjectinterface.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextoption.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttable.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttablecell.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttablecellformat.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttableformat.h
)

list(APPEND GUI_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qabstracttextdocumentlayout_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qcssparser_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfont_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengine_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengine_faceid_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengine_qpf2_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengineglyphcache_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontsubset_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontsubset_agl_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfragmentmap_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qglyphrun_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qinputcontrol_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qrawfont_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qstatictext_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcontrol_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcontrol_p_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcursor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocument_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentfragment_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentlayout_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextengine_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextformat_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexthtmlparser_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextimagehandler_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextobject_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextodfwriter_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttable_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qzipreader_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qzipwriter_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qcssscanner.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qharfbuzz_gui_p.h
)

target_sources(CsGui
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qcssparser.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfont.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengine.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengine_qpf2.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontengineglyphcache.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontsubset.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontmetrics.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qfontdatabase.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qharfbuzz_gui.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qglyphrun.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qinputcontrol.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qrawfont.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qstatictext.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qsyntaxhighlighter.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcontrol.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextengine.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextformat.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextobject.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextoption.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocument.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocument_p.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexthtmlparser.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qabstracttextdocumentlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextcursor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentfragment.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextimagehandler.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtexttable.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextlist.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextdocumentwriter.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qtextodfwriter.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/text/qzip.cpp

   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/autofit/autofit.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftapi.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftbase.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftbbox.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftbdf.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftbitmap.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftcid.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftdebug.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftfstype.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftgasp.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftglyph.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftgxval.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftinit.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftlcdfil.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftmm.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftotval.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftpatent.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftpfr.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftstroke.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftsynth.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftsystem.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/fttype1.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftwinfnt.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/ftxf86.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/base/md5.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/bdf/bdf.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/bzip2/ftbzip2.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/cache/ftccache.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/cache/ftcmanag.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/cache/ftcmru.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/cff/cff.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/cid/type1cid.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/gxvalid/gxvalid.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/gzip/ftgzip.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/lzw/ftlzw.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/otvalid/otvalid.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pcf/pcf.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrcmap.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrdrivr.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrgload.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrload.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrobjs.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pfr/pfrsbit.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/psaux/psaux.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/pshinter/pshinter.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/psnames/psnames.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/raster/raster.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/sfnt/sfnt.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/smooth/smooth.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/truetype/truetype.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/type1/type1.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/type42/type42.c
   ${CS_SOURCE_DIR}/src/3rdparty/freetype/src/winfonts/winfnt.c

   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/fonts/resource_harfbuzz.cpp
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-aat-layout.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-aat-map.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-blob.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-buffer-serialize.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-buffer.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-common.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-face.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-font.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ft.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-map.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-cff1-table.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-cff2-table.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-color.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-face.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-font.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-layout.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-map.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-math.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-name-language.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-name.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-arabic.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-default.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-hangul.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-hebrew.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-indic-table.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-indic.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-khmer.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-myanmar.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-thai.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-use-table.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-use.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-complex-vowel-constraints.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-fallback.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-shape-normalize.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-tag.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-ot-var.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-set.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-shape.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-shape-plan.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-shaper.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-static.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-cff1.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-cff2.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-cff-common.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-glyf.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-input.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-subset-plan.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-unicode.cc
   ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-warning.cc
)

if(GTK2_FOUND)
   target_sources(CsGui
      PRIVATE
      ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-glib.cc
      ${CS_SOURCE_DIR}/src/3rdparty/harfbuzz/src/hb-gobject-structs.cc
   )
endif()
